[package]
name = "forty40"
version = "0.1.2"
authors = ["4meta5 <asinghchrony@protonmail.com>"]
edition = "2018"
description = "generate permutations"
license = "GPL-3.0"
repository = "https://github.com/4meta5/forty40"

[dependencies]
rand = "0.7.3"