[package]
name = "multicomb"
version = "0.1.0"
authors = ["4meta5 <asinghchrony@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-arithmetic = "2.0.0-rc6"
rand = "0.7.3"
